package tech.piis.modules.report.domain.po;

import java.util.Date;

public class CenterReportTypePO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_report_type.ID
     *
     * @mbggenerated Tue Dec 01 16:12:04 CST 2020
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_report_type.REPORT_NAME
     *
     * @mbggenerated Tue Dec 01 16:12:04 CST 2020
     */
    private String reportName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_report_type.REPORT_FREQUENCY
     *
     * @mbggenerated Tue Dec 01 16:12:04 CST 2020
     */
    private String reportFrequency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_report_type.REPORTER
     *
     * @mbggenerated Tue Dec 01 16:12:04 CST 2020
     */
    private String reporter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_report_type.REPORT_TO
     *
     * @mbggenerated Tue Dec 01 16:12:04 CST 2020
     */
    private String reportTo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_report_type.REMARK
     *
     * @mbggenerated Tue Dec 01 16:12:04 CST 2020
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_report_type.CREATED_BY
     *
     * @mbggenerated Tue Dec 01 16:12:04 CST 2020
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_report_type.CREATED_TIME
     *
     * @mbggenerated Tue Dec 01 16:12:04 CST 2020
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_report_type.UPDATED_BY
     *
     * @mbggenerated Tue Dec 01 16:12:04 CST 2020
     */
    private String updatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_report_type.UPDATED_TIME
     *
     * @mbggenerated Tue Dec 01 16:12:04 CST 2020
     */
    private Date updatedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_report_type.ENT_ID
     *
     * @mbggenerated Tue Dec 01 16:12:04 CST 2020
     */
    private String entId;


}