package tech.piis.modules.report.domain.po;

import java.util.Date;

public class CenterReportDocumentPO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_report_document.ID
     *
     * @mbggenerated Tue Dec 01 16:12:04 CST 2020
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_report_document.CENTER_ID
     *
     * @mbggenerated Tue Dec 01 16:12:04 CST 2020
     */
    private String centerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_report_document.FILE_NAME
     *
     * @mbggenerated Tue Dec 01 16:12:04 CST 2020
     */
    private String fileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_report_document.FILE_SIZE
     *
     * @mbggenerated Tue Dec 01 16:12:04 CST 2020
     */
    private Integer fileSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_report_document.FILE_PATH
     *
     * @mbggenerated Tue Dec 01 16:12:04 CST 2020
     */
    private String filePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_report_document.CREATED_BY
     *
     * @mbggenerated Tue Dec 01 16:12:04 CST 2020
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_report_document.CREATED_TIME
     *
     * @mbggenerated Tue Dec 01 16:12:04 CST 2020
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_report_document.UPDATED_BY
     *
     * @mbggenerated Tue Dec 01 16:12:04 CST 2020
     */
    private String updatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_report_document.UPDATED_TIME
     *
     * @mbggenerated Tue Dec 01 16:12:04 CST 2020
     */
    private Date updatedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_report_document.ENT_ID
     *
     * @mbggenerated Tue Dec 01 16:12:04 CST 2020
     */
    private String entId;

}