package tech.piis.modules.report.mapper;

import tech.piis.modules.report.domain.po.CenterReportTypePO ;

public interface CenterReportTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table center_report_type
     *
     * @mbggenerated Tue Dec 01 16:12:04 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table center_report_type
     *
     * @mbggenerated Tue Dec 01 16:12:04 CST 2020
     */
    int insert(CenterReportTypePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table center_report_type
     *
     * @mbggenerated Tue Dec 01 16:12:04 CST 2020
     */
    int insertSelective(CenterReportTypePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table center_report_type
     *
     * @mbggenerated Tue Dec 01 16:12:04 CST 2020
     */
    CenterReportTypePO selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table center_report_type
     *
     * @mbggenerated Tue Dec 01 16:12:04 CST 2020
     */
    int updateByPrimaryKeySelective(CenterReportTypePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table center_report_type
     *
     * @mbggenerated Tue Dec 01 16:12:04 CST 2020
     */
    int updateByPrimaryKey(CenterReportTypePO record);
}