package tech.piis.modules.report.mapper;

import tech.piis.modules.report.domain.po.CenterReportDocumentPO ;

public interface CenterReportDocumentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table center_report_document
     *
     * @mbggenerated Tue Dec 01 16:12:04 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table center_report_document
     *
     * @mbggenerated Tue Dec 01 16:12:04 CST 2020
     */
    int insert(CenterReportDocumentPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table center_report_document
     *
     * @mbggenerated Tue Dec 01 16:12:04 CST 2020
     */
    int insertSelective(CenterReportDocumentPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table center_report_document
     *
     * @mbggenerated Tue Dec 01 16:12:04 CST 2020
     */
    CenterReportDocumentPO selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table center_report_document
     *
     * @mbggenerated Tue Dec 01 16:12:04 CST 2020
     */
    int updateByPrimaryKeySelective(CenterReportDocumentPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table center_report_document
     *
     * @mbggenerated Tue Dec 01 16:12:04 CST 2020
     */
    int updateByPrimaryKey(CenterReportDocumentPO record);
}