package tech.piis.modules.report.mapper;

import tech.piis.modules.report.domain.po.EnterpriseReportDocumentPO ;

public interface EnterpriseReportDocumentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_report_document
     *
     * @mbggenerated Tue Dec 01 16:12:04 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_report_document
     *
     * @mbggenerated Tue Dec 01 16:12:04 CST 2020
     */
    int insert(EnterpriseReportDocumentPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_report_document
     *
     * @mbggenerated Tue Dec 01 16:12:04 CST 2020
     */
    int insertSelective(EnterpriseReportDocumentPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_report_document
     *
     * @mbggenerated Tue Dec 01 16:12:04 CST 2020
     */
    EnterpriseReportDocumentPO selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_report_document
     *
     * @mbggenerated Tue Dec 01 16:12:04 CST 2020
     */
    int updateByPrimaryKeySelective(EnterpriseReportDocumentPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_report_document
     *
     * @mbggenerated Tue Dec 01 16:12:04 CST 2020
     */
    int updateByPrimaryKey(EnterpriseReportDocumentPO record);
}