package tech.piis.modules.report.mapper;

import tech.piis.modules.report.domain.po.EnterpriseReportTypePO ;

public interface EnterpriseReportTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_report_type
     *
     * @mbggenerated Tue Dec 01 16:12:04 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_report_type
     *
     * @mbggenerated Tue Dec 01 16:12:04 CST 2020
     */
    int insert(EnterpriseReportTypePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_report_type
     *
     * @mbggenerated Tue Dec 01 16:12:04 CST 2020
     */
    int insertSelective(EnterpriseReportTypePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_report_type
     *
     * @mbggenerated Tue Dec 01 16:12:04 CST 2020
     */
    EnterpriseReportTypePO selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_report_type
     *
     * @mbggenerated Tue Dec 01 16:12:04 CST 2020
     */
    int updateByPrimaryKeySelective(EnterpriseReportTypePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_report_type
     *
     * @mbggenerated Tue Dec 01 16:12:04 CST 2020
     */
    int updateByPrimaryKey(EnterpriseReportTypePO record);
}